chr1 <- read.table("Bind1.txt")
library(RColorBrewer)
#sequential <- brewer.pal(2, "PuRd")
colors <- c("red","blue")
pdf("Island.pdf", width = 10, height = 10)
#barplot(t(as.matrix(chr)), col = sequential, xlab = "Chromosome", ylab = "Methylation/Mb")
barplot(t(as.matrix(chr1)), col = colors, xlab = "Chromosome", ylab = "Number of DM CpG-Island", axes = TRUE)
#legend("topright", legend = c("Hypermethylation", "Hypomethylation"),fill = sequential[2:1], title = "Direction")
legend("top", legend = c("Hypermethylation", "Hypomethylation"), fill = colors, title = "Island methylation direction")
abline(0,0)
dev.off()