chr <- read.csv("Stacked1.txt", header = TRUE, row.names = 1, sep = "\t")
library(RColorBrewer)
#sequential <- brewer.pal(2, "PuRd")
colors <- c("royalblue4", "firebrick3")
pdf("stacked.pdf", width = 10, height = 10)
#barplot(t(as.matrix(chr)), col = sequential, xlab = "Chromosome", ylab = "Methylation/Mb")
barplot(t(as.matrix(chr)), col = colors, xlab = "Chromosome", ylab = "Methylation/Mb", axes = TRUE)
#legend("topright", legend = c("Hypermethylation", "Hypomethylation"),fill = sequential[2:1], title = "Direction")
legend("topright", legend = c("Hypomethylation", "Hypermethylation"), fill = colors, title = "Direction")
abline(0,0)
dev.off()
